repetitions = 30
output-dir = "benchmark/results"
timeout = 1800

[benchmarks.release-compile]
setup = ["cargo", "fetch", "--locked"]
prepare = ["cargo", "clean", "--release"]
command = ["cargo", "build", "--release", "--locked", "--offline"]
