repetitions = 30
block-size = 4
output-dir = "benchmark/results"
timeout = 1800

[benchmarks.release-compile]
startup = ["cargo", "fetch", "--locked"]
startup-each-run = ["cargo", "clean", "--release"]
command = ["cargo", "build", "--release", "--locked", "--offline"]

[benchmarks.release-test]
startup = ["cargo", "test", "--release", "--locked", "--offline", "--no-run"]
command = ["cargo", "test", "--release", "--locked", "--offline"]
